name: "Chromatic"

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        id: chromatic_publish
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true

  merge-blocking-check:
    runs-on: ubuntu-latest
    needs: chromatic
    steps:
      - name: Wait for Chromatic status check to pass
        id: chromatic_check
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { statuses } } = await github.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            const chromaticStatus = statuses.find(status => status.context === 'Chromatic');
            if (!chromaticStatus || chromaticStatus.state !== 'success') {
              core.setFailed('Chromatic status check is required to pass before merging.');
            }

